Repository namnameeroo/Diabetes, pull requests merged in 2022-12, with the labels that each got.

#100 feat: Add github action file for BE
  .github/workflows/backend-ci-cd.yml
Labels: ✨ Feat, BE

#101 feat: Modify ci/cd file for BE #99
  .github/workflows/backend-ci-cd.yml
Labels: ✨ Feat, BE

#102 chore: Modify ci/cd file for BE #99 2
  .github/workflows/backend-ci-cd.yml
Labels: 🧹 Chore, BE

#103 chore: Modify ci/cd file for BE #99 3
  .github/workflows/backend-ci-cd.yml
Labels: 🧹 Chore, BE

#104 chore: Modify ci/cd file for BE #99 4
  .github/workflows/backend-ci-cd.yml
Labels: 🧹 Chore, BE

#105 chore: Modify ci/cd file for BE #99 5
  .github/workflows/backend-ci-cd.yml
Labels: 🧹 Chore, BE

#106 chore: Modify ci/cd file for BE #99 6
  .github/workflows/backend-ci-cd.yml
Labels: 🧹 Chore, BE

#107 chore: Modify ci/cd file for BE #99 7
  .github/workflows/backend-ci-cd.yml
Labels: 🧹 Chore, BE

#108 Chore:40:UpdateConfigsInvolvingPrettierGitignore
  front-end/.gitignore
  front-end/.prettierrc
  front-end/jsconfig.json
  front-end/package-lock.json
  front-end/package.json
  front-end/src/db.json
Labels: 🧹 Chore, 📄 Docs, FE

#110 Feat:109:updateBaseUrl
  front-end/src/utils.js
Labels: ✨ Feat, FE

#111 fix: Modify backend-cd.yml #99
  .github/workflows/backend-cd.yml
Labels: 🧪 Test, BE

#112 fix: Modify trigger Option #99
  .github/workflows/backend-cd.yml
Labels: 🧹 Chore, BE

#113 fix: Modify trigger Option #99
  .github/workflows/backend-cd.yml
Labels: 🧹 Chore, BE

#114 fix: Modify jar file path #99
  .github/workflows/backend-cd.yml
Labels: 🧹 Chore, 🧪 Test, BE

#115 fix: Modify jar file path #99
  .github/workflows/backend-cd.yml
Labels: 🧹 Chore, 🧪 Test, BE

#116 fix: Modify jar file path #99
  .github/workflows/backend-cd.yml
Labels: 🧹 Chore, 🧪 Test, BE

#117 Feat:97:API형식에맞게키수정
  front-end/src/pages/adminUserList.jsx
Labels: 🛠 Fix, ✨ Feat, FE

#122 Test/121/update food form mylist gl auth
  front-end/src/components/auth.jsx
  front-end/src/components/gl.jsx
  front-end/src/pages/foodForm.jsx
  front-end/src/pages/mylist.jsx
Labels: 🧹 Chore, 🧪 Test, ✨ Feat, FE

#124 Test:123:auth내부메서드를부모에서호출
  front-end/src/api/user.jsx
  front-end/src/components/auth.jsx
  front-end/src/pages/redirect.jsx
Labels: 💔 Invalid, 🧪 Test, FE

#125 Test:123:getAuthWithComponent
  front-end/.gitignore
  front-end/src/App.js
  front-end/src/api/user.jsx
  front-end/src/components/auth.jsx
  front-end/src/components/router.jsx
  front-end/src/pages/mylist.jsx
  front-end/src/pages/redirect.jsx
Labels: 💔 Invalid, 🧪 Test, FE

#126 Test:123:UserInitValueErrorFix
  front-end/src/components/auth.jsx
  front-end/src/pages/redirect.jsx
Labels: 💔 Invalid, 🧪 Test, FE

#127 Test:123:dataFormatEdited #123
  front-end/src/components/auth.jsx
  front-end/src/pages/mylist.jsx
  front-end/src/pages/redirect.jsx
Labels: 🛠 Fix, 💔 Invalid, 🧪 Test, FE

#128 Test:Fix:Feat:123:FixDataKeys and AddRedirect #123
  front-end/src/App.js
  front-end/src/components/auth.jsx
  front-end/src/pages/redirect.jsx
Labels: 🛠 Fix, 🧪 Test, ✨ Feat, FE

#129 Test:123:FixHandlerToLogin #123
  front-end/src/components/auth.jsx
  front-end/src/pages/redirect.jsx
Labels: 🧪 Test, FE

#131 Test:123:RedirectFunctionAddedWithNavigate #123
  front-end/src/App.js
  front-end/src/components/auth.jsx
  front-end/src/pages/redirect.jsx
Labels: 🧪 Test, ✨ Feat, FE

#132 Test:123:Fix:HandleLoginFunctionCallErrorFix #123
  front-end/src/components/auth.jsx
  front-end/src/pages/redirect.jsx
Labels: 🛠 Fix, 🧪 Test, ✨ Feat, FE

#133 Test:123:redirectUseNavCompo and login Check in router about mylist #123
  front-end/src/components/router.jsx
  front-end/src/pages/mylist.jsx
  front-end/src/pages/redirect.jsx
Labels: 🛠 Fix, 🧪 Test, 🧼 Refactor, FE

#134 Test:123:Fix:redirectNavUrlFix #123
  front-end/src/pages/mylist.jsx
  front-end/src/pages/redirect.jsx
Labels: 🛠 Fix, 🧪 Test, FE

#135 Test:123:router조건부렌더링제거 #123
  front-end/src/App.js
  front-end/src/components/router.jsx
  front-end/src/pages/redirect.jsx
Labels: 💔 Invalid, 🧪 Test, FE

#138 Test:123:redirectFixing2
  front-end/src/components/auth.jsx
  front-end/src/components/router.jsx
  front-end/src/pages/redirect.jsx
Labels: 💔 Invalid, 🧹 Chore, 🧪 Test, FE

#139 Test:123:dealingAsyncThen #123
  front-end/src/App.js
  front-end/src/components/auth.jsx
Labels: 🛠 Fix, 🧪 Test, FE

#140 Test:123:redirectTest3 #123
  front-end/.gitignore
  front-end/src/components/auth.jsx
  front-end/src/pages/adminUserList.jsx
  front-end/src/utils.js
Labels: 🪲 Bug, 💔 Invalid, 🧪 Test, FE

#141 Test:123:useLocationToFixRedirect #123
  front-end/src/components/auth.jsx
Labels: 💔 Invalid, 🧪 Test, FE

#145 Feat/style/144/validation logic and gl style update
  front-end/src/components/gl.jsx
  front-end/src/components/toggle.jsx
  front-end/src/pages/foodForm.jsx
  front-end/src/pages/mylist.jsx
  front-end/src/styles/main.css
Labels: 🎨 Design, 🧪 Test, ✨ Feat, FE

#146 Feat:Fix:144:formSubmitNavLinkFix #144 #123
  front-end/src/pages/foodForm.jsx
Labels: 🛠 Fix, ✨ Feat, FE

#148 Style:147:kakaoBtnToYellow #147
  front-end/src/pages/login.jsx
  front-end/src/styles/main.css
Labels: 🎨 Design, 🧹 Chore, FE

#150 Test:Feat:149 prevBtn, top reorder, add top in foodForm #149
  front-end/src/App.js
  front-end/src/components/footer.jsx
  front-end/src/components/top.jsx
  front-end/src/pages/foodForm.jsx
  front-end/src/pages/mylist.jsx
  front-end/src/styles/main.css
Labels: 🧪 Test, ✨ Feat, FE

#151 Test:149:Style:adjustCSS #149
  front-end/src/components/top.jsx
Labels: 🎨 Design, FE

#152 Test:149:Style:loginCss, testLink hidden #149
  front-end/src/pages/login.jsx
  front-end/src/styles/main.css
Labels: 🎨 Design, 🧪 Test, FE

#153 Test:148:Style:Fix fixTestLinkPosition
  front-end/src/styles/main.css
Labels: 🛠 Fix, 🎨 Design, FE

#156 Feat:Test:154: context 분리 후 테스트 #154
  front-end/src/App.js
  front-end/src/components/auth.jsx
  front-end/src/components/userContext.jsx
  front-end/src/pages/login.jsx
  front-end/src/pages/mylist.jsx
  front-end/src/pages/redirect.jsx
Labels: 💔 Invalid, 🧪 Test, FE

#157 Test:154:updateUser in auth test #154
  front-end/.gitignore
  front-end/src/components/auth.jsx
  front-end/src/pages/mylist.jsx
Labels: 🪲 Bug, 💔 Invalid, 🧪 Test, FE

#158 fix: 인증 관련 개발 설정 수정
  back_end/src/main/java/com/diabetes/auth/config/SecurityConfig.java
  back_end/src/main/java/com/diabetes/user/dto/UserDto.java
  back_end/src/main/resources/application.yml
Labels: 🛠 Fix, BE

#159 fix: 배포용 깃헙 액션 수정 #99
  .github/workflows/backend-cd.yml
Labels: 🛠 Fix, 🧹 Chore, BE
