Repository namnameeroo/Diabetes, pull requests merged in 2022-10, with the labels that each got.

#16 files:rename: adminMain to adminUserList #11
  front_end/src/pages/adminUserList.jsx
Labels: 🏷 Rename

#19 styles:chores:14:table style padding adjusted
  front_end/src/pages/mylist.jsx
Labels: 🎨 Design, 🧹 Chore

#20 style:chore:18:font 사이즈 조정 #18
  front_end/src/styles/main.css
Labels: 🎨 Design, 🧹 Chore

#21 Files/11/rename main page to foodForm page
  front_end/src/App.js
  front_end/src/pages/foodForm.jsx
Labels: 🛠 Fix, 🧹 Chore, 🏷 Rename

#23 Feat:Style:main css의 패딩, font color, size 지정하는 클래스 생성 #18
  front_end/src/styles/main.css
Labels: 🎨 Design

#37 fix: 기본crud 및 admin용 Food API 수정 및 추가 #35
  back_end/src/main/java/com/diabetes/food/AdminFoodController.java
  back_end/src/main/java/com/diabetes/food/Food.java
  back_end/src/main/java/com/diabetes/food/FoodService.java
  back_end/src/main/java/com/diabetes/food/GLResult.java
  back_end/src/main/java/com/diabetes/food/dto/FoodDto.java
Labels: back
