Repository namnameeroo/Diabetes, pull requests merged in 2022-11, with the labels that each got.

#39 refactor:fix:11:linkFixByRename #11
  front_end/src/App.js
  front_end/src/pages/foodForm.jsx
Labels: 🛠 Fix, 🧼 Refactor

#41 Chore:40:packageJsonUpdate #40
  front_end/package-lock.json
  front_end/package.json
Labels: 🧹 Chore

#43 Feat:Bug:42:InputDataState #42
  front_end/src/pages/foodForm.jsx
Labels: 🪲 Bug, ✨ Feat

#45 Chore:Docs:DBdataUpdateForFoodForm #42
  front_end/src/db.json
Labels: 🧹 Chore, 📄 Docs, FE

#47 Feat:46:mylistPlusButtonEvent resolve:#46
  front_end/src/components/plusButton.jsx
  front_end/src/pages/mylist.jsx
Labels: 🛠 Fix, ✨ Feat, FE

#49 Fix/34/user api
  back_end/src/main/java/com/diabetes/auth/oauth/KakaoOAuth2UserInfo.java
  back_end/src/main/java/com/diabetes/user/AdminUserController.java
  back_end/src/main/java/com/diabetes/user/domain/AuthProviderType.java
  back_end/src/main/java/com/diabetes/user/domain/User.java
  back_end/src/main/java/com/diabetes/user/domain/UserStatus.java
Labels: BE

#48 fix: Food 도메인 컨트롤러 등 수정 #35
  back_end/src/main/java/com/diabetes/food/AdminFoodController.java
  back_end/src/main/java/com/diabetes/food/Food.java
  back_end/src/main/java/com/diabetes/food/FoodController.java
  back_end/src/main/java/com/diabetes/food/FoodRepository.java
  back_end/src/main/java/com/diabetes/food/FoodService.java
  back_end/src/main/java/com/diabetes/food/dto/FoodDto.java
Labels: 🛠 Fix, BE

#51 Remove/50/remove template files
  front_end/public/favicon.ico
  front_end/src/App.css
  front_end/src/App.test.js
  front_end/src/index.css
  front_end/src/index.js
  front_end/src/logo.svg
  front_end/src/reportWebVitals.js
  front_end/src/setupTests.js
Labels: 🧹 Chore, FE

#52 fix: 페이지네이션 수정 #35
  back_end/src/main/java/com/diabetes/food/AdminFoodController.java
  back_end/src/main/java/com/diabetes/food/FoodController.java
  back_end/src/main/java/com/diabetes/food/FoodRepository.java
  back_end/src/main/java/com/diabetes/food/FoodService.java
Labels: BE

#53 fix: 페이지네이션 수정 #34
  back_end/src/main/java/com/diabetes/user/AdminUserController.java
  back_end/src/main/java/com/diabetes/user/UserService.java
Labels: BE

#56 Refactor:54:RouterComponentIsolation #54
  front_end/src/App.js
  front_end/src/components/router.jsx
Labels: 🪲 Bug, 🧪 Test, 🧼 Refactor, FE

#57 Feat:55:SocialLoginButtonComponentAmend
  front_end/src/pages/login.jsx
Labels: 💔 Invalid, 🧪 Test, ✨ Feat, FE

#58 Chore/40/setting files update
  front_end/.gitignore
  front_end/jsconfig.json
  front_end/package-lock.json
  front_end/package.json
Labels: 🧹 Chore, FE

#60 Feat:59:AuthFileAdded #59
  front_end/src/pages/auth.jsx
Labels: 💔 Invalid, ✨ Feat, FE

#62 Rename:61:RenameRootFolderFE #61 !important
  front-end/.gitignore
  front-end/README.md
  front-end/jsconfig.json
  front-end/package-lock.json
  front-end/package.json
  front-end/public/favicon.ico
  front-end/public/index.html
  front-end/public/logo192.png
  front-end/public/logo512.png
  front-end/public/manifest.json
  front-end/public/robots.txt
  front-end/src/App.js
  front-end/src/components/footer.jsx
  front-end/src/components/plusButton.jsx
  front-end/src/components/router.jsx
  front-end/src/components/top.jsx
  front-end/src/db.json
  front-end/src/index.js
  front-end/src/pages/adminUserList.jsx
  front-end/src/pages/auth.jsx
  front-end/src/pages/foodForm.jsx
  front-end/src/pages/login.jsx
  front-end/src/pages/mylist.jsx
  front-end/src/styles/components.css
  front-end/src/styles/main.css
  front-end/src/utils.js
Labels: 🛠 Fix, 🏷 Rename, FE

#64 Feat:63:fixImportBySettingRootPath
  front-end/src/App.js
  front-end/src/components/footer.jsx
  front-end/src/components/plusButton.jsx
  front-end/src/components/router.jsx
  front-end/src/components/top.jsx
  front-end/src/pages/adminUserList.jsx
  front-end/src/pages/foodForm.jsx
  front-end/src/pages/login.jsx
  front-end/src/pages/mylist.jsx
Labels: 🛠 Fix, 🧼 Refactor, ✨ Feat, FE

#65 Chore:40:RenamePackageNameInConfig #40
  front-end/package-lock.json
  front-end/package.json
Labels: 🧹 Chore, FE

#67 Feat:66:FetchMyFoodList
  front-end/src/pages/mylist.jsx
Labels: 🧪 Test, ✨ Feat, FE

#68 fix: User api 일부 수정 #34
  back_end/src/main/java/com/diabetes/user/AdminUserController.java
  back_end/src/main/java/com/diabetes/user/UserController.java
  back_end/src/main/java/com/diabetes/user/UserRepository.java
  back_end/src/main/java/com/diabetes/user/UserService.java
  back_end/src/main/java/com/diabetes/user/domain/User.java
  back_end/src/main/java/com/diabetes/user/dto/UserDto.java
  back_end/src/main/java/com/diabetes/user/dto/UserResponseDto.java
Labels: BE

#69 Fix:42:다중입력값 업데이트 에러수정 resolve:#42
  front-end/src/pages/foodForm.jsx
Labels: 🛠 Fix, ✨ Feat, FE

#70 Feat:59:EC2배포용 리다이렉트 테스트 #59
  front-end/src/components/router.jsx
  front-end/src/pages/auth.jsx
  front-end/src/pages/mylist.jsx
Labels: 🧪 Test, ✨ Feat, FE

#71 Fix/35/food api
  back_end/src/main/java/com/diabetes/food/AdminFoodController.java
  back_end/src/main/java/com/diabetes/food/Food.java
  back_end/src/main/java/com/diabetes/food/FoodController.java
  back_end/src/main/java/com/diabetes/food/dto/FoodDto.java
Labels: BE

#75 fix: 기타 파일 수정
  back_end/src/main/java/com/diabetes/common/dto/CommonResponse.java
  back_end/src/main/resources/application.yml
  back_end/src/main/resources/data-for-h2.sql
Labels: 🛠 Fix, BE

#76 Feat:42:폼입력값 키수정, 입력일 month 에러수정 #42
  front-end/src/pages/foodForm.jsx
Labels: 🛠 Fix, ✨ Feat, FE

#77 fix: Google Oauth 간소화 수정 #73
  back_end/src/main/java/com/diabetes/auth/oauth/GoogleOAuth2UserInfo.java
Labels: 🛠 Fix, BE

#78 fix: 날짜 정보 응답값에 포함 #35
  back_end/src/main/java/com/diabetes/food/Food.java
  back_end/src/main/java/com/diabetes/food/FoodController.java
  back_end/src/main/java/com/diabetes/food/dto/FoodDto.java
Labels: 🛠 Fix, BE

#79 chore: cors 관련 설정파일 수정 #28
  back_end/src/main/resources/application.yml
Labels: BE

#81 Feat:80:FoodFormValidation
  front-end/src/pages/foodForm.jsx
Labels: 🛠 Fix, ✨ Feat, FE

#83 Feat:82:GetUsersInputList
  front-end/src/pages/mylist.jsx
Labels: ✨ Feat, FE

#84 refactor: food-api 요청/응답 정리 #27
  back_end/src/main/java/com/diabetes/food/AdminFoodController.java
  back_end/src/main/java/com/diabetes/food/Food.java
  back_end/src/main/java/com/diabetes/food/FoodController.java
  back_end/src/main/java/com/diabetes/food/FoodService.java
  back_end/src/main/java/com/diabetes/food/dto/FoodReqDto.java
  back_end/src/main/java/com/diabetes/food/dto/FoodResDto.java
  back_end/src/main/java/com/diabetes/food/dto/FoodSimpleResDto.java
Labels: 🧼 Refactor, BE

#85 fix: user-api 기능 보완 및 수정 #34
  back_end/src/main/java/com/diabetes/user/AdminUserController.java
  back_end/src/main/java/com/diabetes/user/RoleTypeSetConverter.java
  back_end/src/main/java/com/diabetes/user/UserService.java
  back_end/src/main/java/com/diabetes/user/domain/User.java
  back_end/src/main/java/com/diabetes/user/dto/AdminSecretDto.java
  back_end/src/main/java/com/diabetes/user/dto/UserResponseDto.java
Labels: 🛠 Fix, BE

#86 fix: 커스텀 예외의 디폴트 http status(400) 지정 #38
  back_end/src/main/java/com/diabetes/common/exception/BadRequestException.java
  back_end/src/main/java/com/diabetes/common/exception/CustomApiException.java
Labels: 🛠 Fix, BE

#87 fix: 소셜 로그인시 null 데이터 제어 보완
  back_end/src/main/java/com/diabetes/auth/oauth/KakaoOAuth2UserInfo.java
  back_end/src/main/java/com/diabetes/auth/oauth/OAuth2UserInfo.java
Labels: 🪲 Bug, 🛠 Fix, BE

#88 chore: 컬럼명 변경에 따른 test sql 수정 #28
  back_end/src/main/resources/data-for-h2.sql
Labels: 🧹 Chore, BE

#96 Test/93/1st deployment
  front-end/jsconfig.json
  front-end/src/App.js
  front-end/src/components/plusButton.jsx
  front-end/src/components/router.jsx
  front-end/src/components/toggle.jsx
  front-end/src/components/top.jsx
  front-end/src/db.json
  front-end/src/index.js
  front-end/src/pages/auth.jsx
  front-end/src/pages/foodForm.jsx
  front-end/src/pages/login.jsx
  front-end/src/pages/mylist.jsx
  front-end/src/styles/main.css
  front-end/src/utils.js
Labels: 🧪 Test, FE

#98 Feat:97:UserListAPI #97
  front-end/src/pages/adminUserList.jsx
Labels: FE
