Repository namnameeroo/Diabetes, pull requests merged in 2023-04, with the labels that each got.

#233 Fix/food
  back_end/src/main/java/com/diabetes/auth/oauth/KakaoOAuth2UserInfo.java
  back_end/src/main/java/com/diabetes/food/Food.java
Labels: 🛠 Fix, BE

#234 Refactor/fix/207/refactoring
  front-end/public/index.html
  front-end/src/layout/AuthLayout.jsx
Labels: 🛠 Fix, ✨ Feat, FE

#235 Refactor/fix/207/refactoring #207
  front-end/src/components/plusButton.jsx
  front-end/src/layout/AuthLayout.jsx
Labels: 🛠 Fix, 🎨 Design, FE

#237 Refactor/fix/207/refactoring #207
  front-end/src/db.json
  front-end/src/pages/FoodFormPage.jsx
  front-end/src/pages/MylistPage.jsx
  front-end/src/pages/RedirectPage.jsx
  front-end/src/pages/UserlistPage.jsx
  front-end/src/router.jsx
Labels: 🧪 Test, ✨ Feat, FE

#238 Refactor/fix/207/refactoring
  front-end/src/components/plusButton.jsx
  front-end/src/pages/LoginPage.jsx
Labels: 🎨 Design, 🧪 Test, FE

#239 Refactor:Fix:207:Logout Button, remove Cookie 수정 #207
  front-end/src/components/logoutButton.jsx
Labels: 🧪 Test, FE

#240 Refactor:Fix:207:plusButton size error in mobile safari again #207
  front-end/src/components/plusButton.jsx
Labels: 🛠 Fix, 🎨 Design, FE

#242 Refactor:Fix:207:plusButton resize #207
  front-end/public/index.html
  front-end/src/components/plusButton.jsx
Labels: 🎨 Design, 🧹 Chore, FE

#243 Refactor:Fix:207:plusButton resize #207
  front-end/src/components/plusButton.jsx
Labels: 🛠 Fix, 🎨 Design, FE

#244 Refactor/fix/207/refactoring
  front-end/src/components/logoutButton.jsx
  front-end/src/components/top.jsx
  front-end/src/pages/FoodFormPage.jsx
  front-end/src/pages/MylistPage.jsx
  front-end/src/pages/RedirectPage.jsx
  front-end/src/styles/main.css
Labels: 🎨 Design, 🧹 Chore, FE

#245 Refactor:Fix:207: validation 실행 로직 수정, form button style 통일시킴 #207
  front-end/src/api/foodForm.jsx
  front-end/src/components/toggle.jsx
  front-end/src/layout/AuthLayout.jsx
  front-end/src/pages/FoodFormPage.jsx
  front-end/src/pages/UserlistPage.jsx
Labels: 🛠 Fix, FE

#246 Refactor:Fix:207:AuthLayout내부 async 잘못된 사용 제거
  front-end/src/layout/AuthLayout.jsx
Labels: 🛠 Fix, 🧪 Test, FE

#247 Refactor:207:유저 목록, 테스트 계정들 제거
  front-end/src/pages/UserlistPage.jsx
Labels: 🛠 Fix, 🧼 Refactor, FE

#248 Refactor:Fix:Test:207: 오류때문에 임시로 id=null받고, Auth에서 role세팅 잘못되고 있는거 수정
  front-end/src/layout/AuthLayout.jsx
  front-end/src/pages/UserlistPage.jsx
Labels: 🛠 Fix, 🧼 Refactor, FE

#249 Refactor:Fix:Test:207: 오류때문에 임시로 id=null받기
  front-end/src/pages/UserlistPage.jsx
Labels: 🧪 Test, FE

#250 Refactor:Fix:Test:207: 오류때문에 임시로 email=null인 유저도 목록에 표시
  front-end/src/pages/UserlistPage.jsx
Labels: 🛠 Fix, FE

#251 Refactor/fix/207/refactoring TryCatch in 폼입력, print추가 in AuthLayer
  front-end/src/api/foodForm.jsx
  front-end/src/layout/AuthLayout.jsx
Labels: 🛠 Fix, 🧪 Test, FE

#252 Feat:236:Test:userID 넘어가는지, navigate 값전달 사용 #236
  front-end/src/pages/FoodFormPage.jsx
  front-end/src/pages/MylistPage.jsx
Labels: 🧪 Test, FE

#253 Feat:236:Test:userID 넘어가는지, useLocation 값전달 사용 #236
  front-end/src/pages/FoodFormPage.jsx
Labels: 🛠 Fix, FE

#254 Feat:236:Test:Fix: userID 넘어가는지, useLocation 값전달 사용 #236
  front-end/src/pages/MylistPage.jsx
Labels: 🛠 Fix, 🧪 Test, FE

#256 Feat/236/test/update form by admin, UserId 넘기기
  front-end/src/pages/FoodFormPage.jsx
  front-end/src/pages/MylistPage.jsx
  front-end/src/pages/UserlistPage.jsx
Labels: 💔 Invalid, 🧪 Test, FE

#257 Feat:236:Fix: update by admin api요청할 때, 성공반환에도 실패모달뜨는 로직 수정 #236
  front-end/src/pages/FoodFormPage.jsx
Labels: 🛠 Fix, FE

#262 Feat:236:Fix: update by admin api요청 에러 수정, 콘솔정리 #236
  front-end/src/api/foodForm.jsx
  front-end/src/components/gl.jsx
  front-end/src/pages/FoodFormPage.jsx
Labels: 🛠 Fix, 🧪 Test, FE

#264 Feat:236:Fix: getByAdmin api 추가 및 관련 로직수정 #236
  front-end/src/api/foodForm.jsx
  front-end/src/pages/FoodFormPage.jsx
Labels: 🛠 Fix, FE

#265 Feat:236:Fix: getByAdmin api 추가 및 관련 로직수정, api import #236
  front-end/src/api/foodForm.jsx
  front-end/src/pages/FoodFormPage.jsx
Labels: 🧪 Test, FE

#267 Fix:266:userlustGender표시 수정 #266
  front-end/src/pages/UserlistPage.jsx
Labels: 🛠 Fix, FE

#269 Fix:268:Test: auth useCallback의 인자 수정 #268
  front-end/src/layout/AuthLayout.jsx
Labels: 🛠 Fix, FE

#271 Style:270:CardDesignAdapted #270
  front-end/src/components/plusButton.jsx
  front-end/src/components/top.jsx
  front-end/src/pages/MylistPage.jsx
  front-end/src/pages/UserlistPage.jsx
  front-end/src/styles/main.css
Labels: 🎨 Design, FE

#273 Style:270:Fix:FoodForm Buttons Position Bug #270
  front-end/src/components/toggle.jsx
  front-end/src/pages/FoodFormPage.jsx
  front-end/src/styles/main.css
Labels: 🛠 Fix, 🎨 Design, FE
