Repository namnameeroo/Diabetes, pull requests merged in 2023-01, with the labels that each got.

#160 Feat:154:LoginContext:Test:useContext Logic amend #154
  front-end/src/App.js
  front-end/src/components/auth.jsx
  front-end/src/components/userContext.jsx
  front-end/src/pages/mylist.jsx
  front-end/src/pages/redirect.jsx
  front-end/src/utils.js
Labels: 🧪 Test, FE

#162 Fix:161:nullUserErrorFixed #161
  front-end/src/pages/adminUserList.jsx
Labels: 🛠 Fix, FE

#163 Feat/154/test/login context test
  front-end/src/pages/foodForm.jsx
  front-end/src/utils.js
Labels: 🛠 Fix, 🧪 Test, FE

#164 fix: 깃헙 액션 파일 수정 및 run.sh 추가
  .github/workflows/backend-cd.yml
  back_end/run.sh
Labels: 🛠 Fix

#165 fix: 파일명 수정 및 깃헙 액션 트리깅 테스트 #99
  .github/workflows/backend-ci-cd.yml
Labels: 🛠 Fix

#167 fix: 실행 명령어 수정 #99
  .github/workflows/backend-ci-cd.yml
Labels: 🛠 Fix

#168 fix: 스크립트 로그 출력 수정 #99
  back_end/run.sh
Labels: 🛠 Fix

#169 Feat/154/test/login context test
  front-end/src/App.js
  front-end/src/components/auth.jsx
  front-end/src/components/router.jsx
  front-end/src/components/userContext.jsx
  front-end/src/pages/adminUserList.jsx
  front-end/src/pages/foodForm.jsx
  front-end/src/pages/login.jsx
  front-end/src/pages/mylist.jsx
  front-end/src/pages/redirect.jsx
  front-end/src/utils.js
Labels: 🧪 Test, ✨ Feat, FE

#171 Fix/170/null error fixed
  front-end/src/App.js
  front-end/src/components/auth.jsx
  front-end/src/pages/adminUserList.jsx
  front-end/src/pages/foodForm.jsx
  front-end/src/pages/login.jsx
  front-end/src/pages/mylist.jsx
  front-end/src/pages/redirect.jsx
  front-end/src/utils.js
Labels: 🛠 Fix, FE

#174 Fix:173:AdminPropsKeyErrorFixed
  front-end/src/pages/adminUserList.jsx
Labels: 🛠 Fix, FE

#176 Feat:175:리다이렉트 컴포넌트에서 Navigate by role,auth상태
  front-end/src/pages/redirect.jsx
Labels: ✨ Feat, FE

#177 Refactor:Fix:175:auth component render order fixing in public server #175
  front-end/src/components/auth.jsx
  front-end/src/components/userContext.jsx
  front-end/src/pages/adminUserList.jsx
  front-end/src/pages/foodForm.jsx
  front-end/src/pages/login.jsx
  front-end/src/pages/mylist.jsx
  front-end/src/pages/redirect.jsx
Labels: 🪲 Bug, 🛠 Fix, 🧼 Refactor, FE

#178 Fix:173:UsersInfoDataFormatFix Temorarily #173
  front-end/src/pages/adminUserList.jsx
Labels: 🛠 Fix, 💔 Invalid, FE

#180 Fix:179:MylistRoleCheckAmend
  front-end/src/pages/mylist.jsx
Labels: 🛠 Fix, FE

#181 Test:154:contextDataFormatTest #154
  front-end/src/components/userContext.jsx
Labels: 🧪 Test, FE

#182 fix: 날짜 데이터 관련 응답값 수정
  back_end/src/main/java/com/diabetes/food/dto/FoodReqDto.java
  back_end/src/main/java/com/diabetes/food/dto/FoodResDto.java
  back_end/src/main/java/com/diabetes/user/domain/User.java
  back_end/src/main/java/com/diabetes/user/dto/UserResponseDto.java
Labels: 🛠 Fix, BE

#184 Test:154:redirectPageErrorFixTest #154
  front-end/src/components/auth.jsx
  front-end/src/pages/redirect.jsx
Labels: 🛠 Fix, 🧪 Test, FE

#186 Fix:154:RedirectPageAuthUserGet #154
  front-end/src/components/auth.jsx
  front-end/src/pages/redirect.jsx
Labels: 🛠 Fix, FE

#187 Fix:154:Test:removeAuthCompInApp,moveNavigateToAuthComp #154
  front-end/src/App.js
  front-end/src/components/auth.jsx
  front-end/src/pages/redirect.jsx
Labels: 🛠 Fix, 🧪 Test, FE

#188 Test:154:redirectInAuth...Again..checkByRowData
  front-end/src/components/auth.jsx
  front-end/src/pages/redirect.jsx
Labels: 🧪 Test, FE

#189 Chore:40:DS_StoreAddInGitignore #40
  front-end/.gitignore
Labels: 🧹 Chore, FE

#190 Feat:185:Style:foodInfoComponentAndStyles #185
  front-end/src/pages/foodForm.jsx
  front-end/src/styles/main.css
Labels: 🧪 Test, ✨ Feat, FE

#191 Feat:185:Fix:getFoodInfoDataFormatAmend #185
  front-end/src/pages/foodForm.jsx
Labels: 🛠 Fix, FE

#192 Merge pull request #191 from namnameeroo/feat/185/getFoodFormInfo
  front-end/src/pages/foodForm.jsx
Labels: 🛠 Fix, 🧹 Chore, 🧪 Test, FE

#193 Fix:Test:154:redirectPageSyncInAuthBug #154
  front-end/src/components/auth.jsx
  front-end/src/components/router.jsx
  front-end/src/components/userContext.jsx
  front-end/src/pages/foodForm.jsx
  front-end/src/pages/redirect.jsx
Labels: 🧪 Test, ✨ Feat, FE

#194 Feat:185:getFoodFormInfoCell #185
  front-end/src/pages/foodForm.jsx
Labels: 🛠 Fix, 💔 Invalid, ✨ Feat, FE

#195 Fix/173/admin user list created date data
  front-end/src/pages/adminUserList.jsx
Labels: 🛠 Fix, FE

#196 Feat:185:Fix:foodInfoDataset...
  front-end/src/pages/foodForm.jsx
Labels: 🛠 Fix, ✨ Feat, FE

#198 Feat:185:Fix:getFoodInfoStateVarAdded #185
  front-end/src/pages/foodForm.jsx
Labels: 🛠 Fix, ✨ Feat, FE
